version: '3.8'  # Certifique-se de especificar a versão do Compose
services:
  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASS}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Use volumes nomeados para persistência
    ports:
      - '6222:5432'

volumes:
  postgres_data:
